### ISSUE TITLE
Failed to call timer_cb errors

### ISSUE THREAD

**Issue by Xaenchan** [nosjo/obs-vrchat-log-reader#1]
![obs](https://github.com/nosjo/obs-vrchat-log-reader/assets/138818240/046db121-18f3-4a57-8b6e-f3d04276ddb9)

i get those errors trying to use the script

**Comment by nosjo** [comment]
So this seems to happen if the script cant find a log file from vrchat, i will make it output a proper error message instead in next update

**Comment by nosjo** [comment]
Made a new pre-release that gives better errors when this happens and allows for manual path to the vrchat log folder
https://github.com/nosjo/obs-vrchat-log-reader/releases/tag/1.0.3
